### PR TITLE
Minor typo in a rule description

### PR DESCRIPTION
**Pull request by javiereguiluz**

### CODE REVIEW

**Comment by OskarStark** [comment]
Can you please fix the [test](https://github.com/OskarStark/doctor-rst/blob/master/tests/Rule/OrderedUseStatementsTest.php)?

**Comment by javiereguiluz** [comment]
I've created this PR directly in GitHub ... I don't know how can I add more changes to this PR.

**Comment by OskarStark** [comment]
Go to the mainpage, select you branch, browse to the test, change it and your PR gets updated automatically, because it reflect the branch changes.
Was that easy to understand? 🙃

**Comment by javiereguiluz** [comment]
Nice! Perfectly explained. Thanks Oskar.

**Pull request merged**
