### PR TITLE
php8 compatibility

### PR DESCRIPTION
**Pull request by smoench**

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Thank you very much 🥰

**Comment by smoench** [comment]
Unfortunately, we need to wait for stable 8.0 docker images.

**Comment by OskarStark** [comment]
Any significant performance increase using php 8?

**Comment by OskarStark** [comment]
Images are available, right?

**Comment by smoench** [comment]
Sure, but not for x86-64 (only arm, ppc and s390) 🙈

**Comment by smoench** [comment]
amd64 architecture is now available but box seems to have a problem. Might be related to https://github.com/box-project/box/issues/489
```
 ---> 1d6fb4c0c879
Step 7/19 : ADD https://github.com/humbug/box/releases/download/3.10.0/box.phar ./box.phar
Downloading [==================================================>]   1.89MB/1.89MB
 ---> 30a4fd1945dc
Step 8/19 : RUN php box.phar compile
 ---> Running in f81d5263f939

Box Requirements Checker
========================

> Using PHP 8.0.0
> PHP is using the following php.ini file:
  WARNING: No configuration file (php.ini) used by PHP!

> Checking Box requirements:
  E.....


 [ERROR] Your system is not ready to run the application.


Fix the following mandatory requirements:
=========================================

 * The application requires the version "^7.3" or greater.

The command '/bin/sh -c php box.phar compile' returned a non-zero code: 1
```
Or box is not ready for PHP 8 but I'm already working on it https://github.com/humbug/php-scoper/pull/446 (first php-scoper needs be php 8 compatible then box can be updated).

**Comment by OskarStark** [comment]
Any news on this @smoench ?

**Comment by smoench** [comment]
Still in progress https://github.com/box-project/box/pull/508

**Comment by OskarStark** [comment]
Looks like its passing, right?

**Comment by smoench** [comment]
Yes, it passes now. Just had adjust the `Dockerfile`

**Review by OskarStark — APPROVED** [review]

**Pull request merged**
