### PR TITLE
New Rule `TitleUnderlineLengthMustMatchTitleLength`

### LINKED ISSUE #1271: Underline (for headlines) length should match
Not sure about the rule name yet 🤔 

Follows https://github.com/symfony/symfony-docs/pull/17482/files#r1090257160

### PR DESCRIPTION
**Pull request by MrYamous**
Fixes #1271

### CODE REVIEW

**Comment by OskarStark** [comment]
Oh nice, I will review in detail later 🙏

I am currently on a phone 📱

**Comment by OskarStark** [comment]
> Documentation / Generate (8.2) (pull_request) 
You can ignore this CI step

I would rename the rule to `HeadlineUnderlineLengthMustMatchHeadlineLength`. What do you think? It is more descriptive and not every headline marks describes a "Section" 🤔

**Comment by MrYamous** [comment]
> > Documentation / Generate (8.2) (pull_request)
> > You can ignore this CI step
> 
> I would rename the rule to `HeadlineUnderlineLengthMustMatchHeadlineLength`. What do you think? It is more descriptive and not every headline marks describes a "Section" thinking

I agree this name looks good, or maybe `TitleUnderlineLengthMustMatchTitleLength` ?
`HeadlineUnderline` sounds a bit redundant to me

**Comment by OskarStark** [comment]
You are right, lets go with:
`TitleUnderlineLengthMustMatchTitleLength`

**Comment by OskarStark** [comment]
I created a release, the image is now built on dockerhub, once available (maybe in 10 minutes) can you please create a PR against the `symfony/symfony-docs` repo and use the latest version and add the rule to `.doctor-rst.yaml` file? thanks

**Pull request merged**
