### PR TITLE
Remove some layer and redundancy in the final Docker image

### PR DESCRIPTION
**Pull request by tucksaun**
⚠️ I didn't build it locally

### CODE REVIEW

**Comment by OskarStark** [comment]
How would this work without adding the file, if it is then distributed as a standalone built image?

**Comment by smoench** [comment]
It is added in line 14 with: `ADD . /usr/src/app`

**Comment by tucksaun** [comment]
Exactly 😀

>

**Comment by smoench** [comment]
Well, this is just a "tiny" improvement. The most you will get from using an alpine base image :-) But depends from goal of this project. Should this be a CLI-Tool or also web-based?

**Comment by OskarStark** [comment]
> It is added in line 14 with: ADD . /usr/src/app

You are right 👍 

> The most you will get from using an alpine base image :-)

Open for a PR @smoench 👍 

> Should this be a CLI-Tool or also web-based?

Its mostly used via GithubActions and having smaller images would result in faster feedback...

**Comment by OskarStark** [comment]
Thank you @tucksaun

**Pull request merged**
