### PR TITLE
Perf optimize `Line::isDefaultDirective()`

### PR DESCRIPTION
**Pull request by staabm**
grafik

### CODE REVIEW

**Comment by staabm** [comment]
I wonder why after this change we also have less use of `str_contains`

grafik

it seems I am missing something obvious which is not covered by the unit test-cases for `Line`

**Comment by OskarStark** [comment]
Hmm, a few tests break after your change, maybe that's the cause for the less `str_contains()`?

**Comment by staabm** [comment]
could you give me an idea about these tests. I have 0 experience with .rst.

maybe you could extract something from the failling tests which can be reflected in the unit test?

**Comment by staabm** [comment]
nevermind. should be good to go @OskarStark

**Comment by staabm** [comment]
@OskarStark this is the last one open.

**Comment by OskarStark** [comment]
Thanks <3

**Pull request merged**
