### PR TITLE
Add `RulesConfiguration`

### PR DESCRIPTION
**Pull request by alamirault**
To fix https://github.com/symfony/symfony-docs/pull/18295 we have to exclude file from all rules or add 15 `whitelist` rules in `.doctor-rst.yaml`.

This PR is needed to be able to exclude rule by file in a follow-up PR

```yaml
rules:
  ...
exclude_rule_for_file:
  - path: configuration/multiple_kernels.rst
    rule_name: replacement
```

Refs #1340

### CODE REVIEW

**Comment by OskarStark** [comment]
Can we create the service for the rules before hand in a separate PR?

**Comment by alamirault** [comment]
@OskarStark I split commit

(Following will looks like https://github.com/OskarStark/doctor-rst/commit/99891272620988bb451ac2ca3ae45c0b00e2f2e5)

**Comment by OskarStark** [comment]
Looks good to me 👌🏻👍🏻😎

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
SO this PR is only about the RulesConfiguration, correct?

**Comment by OskarStark** [comment]
@alamirault you can go ahead 👍

**Pull request merged**
